dist: bionic
language: crystal

build_addons: &build_addons
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - libgit2-dev
    - libsass-dev

crystal:
- latest

cache:
- shards
- directories:
  - vendor/

env:
  global:
    - PGPORT: 5433
    - TEST_DATABASE_URL: "postgres://postgres:@localhost:5433/shardbox"
    - DBMATE: "vendor/bin/dbmate"

jobs:
  include:
  - stage: test
    name: unit tests
    services:
    - postgresql
    addons: *build_addons
    before_script:
    - ./lib/shardbox-core/.travis/setup-database.sh
    - make -C ./lib/shardbox-core test_db
    script: make test

  - stage: test
    name: crystal format
    install: skip
    script: crystal tool format src spec --check

  - stage: test
    name: integration test
    services:
    - postgresql
    addons: *build_addons
    before_script:
    - ./lib/shardbox-core/.travis/setup-database.sh
    - make -C ./lib/shardbox-core test_db
    script: ./.travis/integration-spec.sh

  - stage: test
    name: build docker container
    services:
    - docker
    script: docker build .

  - stage: deploy
    name: dokku
    language: generic
    addons:
      ssh_known_hosts: shardbox.org
    deploy:
      provider: script
      script: .travis/deploy.sh
      on:
        branch: master
    if: branch = master
